from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from agent.config import REPORTS_DIR, ensure_data_dirs
from agent.models import Finding, ReconState, ScanRun, Severity


SEVERITY_ORDER = {
    Severity.CRITICAL: 0,
    Severity.HIGH: 1,
    Severity.MEDIUM: 2,
    Severity.LOW: 3,
    Severity.INFO: 4,
}


def write_report(run: ScanRun) -> Path:
    ensure_data_dirs()
    findings = sorted(run.findings, key=lambda f: SEVERITY_ORDER.get(f.severity, 9))
    recon = run.recon
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    counts = {s.value: 0 for s in Severity}
    for f in findings:
        counts[f.severity.value] += 1

    md_lines = [
        f"# Prism Findings Report",
        "",
        f"**Run ID:** `{run.id}`  ",
        f"**Target:** `{run.target}`  ",
        f"**Generated:** {now}  ",
        f"**Mode:** {run.mode} (read-only, allowlisted)  ",
        "",
        "## Executive summary",
        "",
        f"Prism completed an autonomous recon → misconfig pass on `{run.target}`. "
        f"It recorded **{len(findings)}** findings "
        f"({counts['critical']} critical, {counts['high']} high, "
        f"{counts['medium']} medium, {counts['low']} low, {counts['info']} info).",
        "",
        "All actions were **read-only**. No exploitation was performed. "
        "Every step is in the audit log for human review.",
        "",
        "## Severity breakdown",
        "",
        "| Severity | Count |",
        "|---|---|",
    ]
    for sev in Severity:
        md_lines.append(f"| {sev.value} | {counts[sev.value]} |")

    md_lines += ["", "## Attack surface snapshot", ""]
    if recon:
        md_lines += [
            f"- **Host:** {recon.host}",
            f"- **Base URL:** {recon.base_url}",
            f"- **Technologies:** {', '.join(recon.technologies) or 'n/a'}",
            f"- **Open ports:** "
            + (
                ", ".join(f"{p['port']}/{p.get('service', '?')}" for p in recon.open_ports)
                or "none detected in scan set"
            ),
            f"- **Subdomains:** {', '.join(recon.subdomains) or recon.host}",
            f"- **Interesting paths:** {', '.join(recon.interesting_paths[:20]) or 'none'}",
            "",
        ]

    md_lines += ["## Prioritized findings", ""]
    if not findings:
        md_lines.append("_No material misconfigurations detected in the passive pass._")
    for i, f in enumerate(findings, 1):
        md_lines += [
            f"### {i}. [{f.severity.value.upper()}] {f.title}",
            "",
            f"- **Category:** {f.category}",
            f"- **Asset:** `{f.asset or run.target}`",
            f"- **Confidence:** {f.confidence:.0%}",
            f"- **CWE:** {f.cwe or 'n/a'}",
            f"- **Evidence:** {f.evidence}",
            f"- **Remediation:** {f.remediation}",
        ]
        if f.references:
            md_lines.append("- **References:** " + ", ".join(f.references))
        md_lines.append("")

    md_lines += [
        "## Human-in-the-loop notes",
        "",
        "- Allowlist gate enforced before any network action.",
        "- CMS deep checks and anything marked `needs_human` require explicit approval.",
        "- Audit trail: `data/audit/{run_id}.jsonl`.",
        "",
        "---",
        "_Generated by Prism — Agentic Attack Surface Mapper_",
    ]

    path = REPORTS_DIR / f"{run.id}.md"
    path.write_text("\n".join(md_lines), encoding="utf-8")

    json_path = REPORTS_DIR / f"{run.id}.json"
    json_path.write_text(
        json.dumps(
            {
                "run_id": run.id,
                "target": run.target,
                "status": run.status,
                "counts": counts,
                "findings": [f.model_dump(mode="json") for f in findings],
                "recon": recon.model_dump(mode="json") if recon else None,
                "report_markdown": str(path),
            },
            indent=2,
            default=str,
        ),
        encoding="utf-8",
    )
    return path


def finding_to_card(f: Finding) -> dict:
    return {
        "id": f.id,
        "title": f.title,
        "severity": f.severity.value,
        "category": f.category,
        "evidence": f.evidence,
        "remediation": f.remediation,
        "asset": f.asset,
        "cwe": f.cwe,
        "confidence": f.confidence,
    }